### ISSUE TITLE
Error when attempting catalog search

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist-dl#750] opened 2024-04-12 14:12 UTC
Since the Knapsack upgrade, about 3/4 of the time I enter a term in the catalog search box on production (either tenant, and from any location--home page, a work page, a collection page, etc.), the site fails to load and I get a "Sorry, something went wrong" error message. Below are screenshots on ADL prod of a search from the homepage and from a work page. 

![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/b51efecb-0e17-4a95-8205-135e48a2a376)

https://adl.b2.adventistdigitallibrary.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=Spectrum
![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/5e0f3db4-6a00-4d54-bed1-1c32bb444ced)

![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/34e4f4da-4790-49f3-8d92-1655c1024ca3)

https://adl.b2.adventistdigitallibrary.org/catalog?utf8=%E2%9C%93&parent_query=The+First+Report+of+the+General+Conference+of+Christians+Expecting+the+Advent+of+the+Lord+Jesus+Christ%2C+Held+in+Boston%2C+Oct.+14%2C+15%2C+1840&search_field=all_fields&q=cardinal
![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/78fbc666-fbe2-4db1-9069-62a4225df852)

SDAPI example, to show it's happening on multiple tenants:

https://sdapi.b2.adventistdigitallibrary.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=spectrum
![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/4a0592ce-2146-4f2b-aa8e-9c264dd53ec7)

**Comment by ShanaLMoore** [comment] 2024-04-13 04:10
Confirmed I am seeing this issue with the [link](https://adl.b2.adventistdigitallibrary.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=Spectrum) provided. There are no sentry errors logged due to rate limits. 



[adventist-knapsack-production-hyrax-57856cd456-tv97m_hyrax.log](https://github.com/scientist-softserv/adventist-dl/files/14965141/adventist-knapsack-production-hyrax-57856cd456-tv97m_hyrax.log)

**Comment by ShanaLMoore** [comment] 2024-04-15 19:11
QA: PASS ✅ 

Searched for the word "minute" returned results. 




![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/052fd776-6bab-4a76-8401-bd8375fd34eb)


Searched for "spectrum" correctly did not return results (because the [test tenant ](https://staging.adventist-knapsack-staging.notch8.cloud/catalog?utf8=%E2%9C%93&parent_query=minute&search_field=all_fields&q=spectrum)doesn't have this data): 



![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/93556eed-afd7-4f85-bf99-a86dd5874f1f)




Empty search: 



![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/bcd5b9ca-c592-4f79-b0ca-3a30bb787c1d)

**Comment by KatharineV** [comment] 2024-04-18 15:13
Friends, I still get the "We're sorry but something went wrong" error message about 1/3rd of the time when I attempt a catalog search. :(  I can't always replicate the behavior, but it happens seemingly at random during attempted searches of all kinds. Screenshots below show one example search URL that failed to load in multiple tests.

I can confirm the catalog search is erroring on ADL production. It errors in multiple browsers (tested Edge, Chrome, and Firefox). It errors when I am logged in and when I am logged out.

Prod search, logged in, using Firefox. Term was "medical." I searched from the homepage and from the search bar on a work page and got the same error message result.

![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/9e38a8a0-07fb-499b-8431-be93ea8a0db3)

Prod search, logged out, using Edge. Term was "medical."

![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/e58cb6af-721a-413d-92c9-526525b48a3a)

This term has consistently failed to return a result. Three times in a row, I've reloaded the ADL homepage, searched "medical," and gotten the error message. I hope this information is helpful.

**Comment by ShanaLMoore** [comment] 2024-04-18 17:09
@KatharineV I understand your frustration. Perhaps our demo caught it on a "good" time since it appears to be intermittent. I'm able recreate this issue too, with the term "medical", so thanks for finding that example. Moving this ticket back for rework.

**Comment by orangewolf** [comment] 2024-04-22 00:13
@KatharineV the "Something went wrong" pages on these searches should all be resolved now. Certain types of documents were triggering this if they appeared in the results. So some results had the error where others did not. I am fairly confident that I've now covered all the different kinds of results (different work types, collections, etc) and we won't see this specific error again.

**Comment by KatharineV** [comment] 2024-04-22 17:22
I tested the three search terms that used to throw an error message on ADL prod (Spectrum, cardinal, & medical). The catalog search worked for all three terms and returned results as expected. Thank you!

**Closed** 2024-04-22 17:42 UTC
Labels: bug, Needs Rework, Knapsack Upgrade
