### ISSUE TITLE
Custom Font Issues

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/adventist-dl#590] opened 2023-09-29 18:04 UTC
## 1. Double Rendering
Font selection works in spite of the duplication of select fields.

![Image](https://github.com/scientist-softserv/adventist-dl/assets/17851674/c76c13e5-c7e3-4131-8812-7b5e8b6e9aa2)

- [x] Font input should only show once on tab

## 2. No Font Preview

- [x] Font options shows a preview of what the font looks like

### Staging examples

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/5b22cb63-0fae-48e7-ad58-eb8fc9b515df)

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/a9fc4672-3f1f-4575-ab83-d82d9a761b8c)

# Testing Instructions
Visit https://demo.adventist-knapsack-staging.notch8.cloud/admin/appearance?locale=en#font  (Admin Dashboard > Settings > Appearance > Font Tab
- [ ] DOUBLE RENDERING: There should be 1 input field for each option (Select Body Font and Select Header Font)
- [ ] NO FONT DEFAULT PREVIEW:
  - Disregard. This is a known bug in hyku that we will not fix in this epic of work. Currently the user has to select an option of the dropdown to see the fonts displayed.

**Comment by ShanaLMoore** [comment] 2023-10-04 22:54
commenting out the javascript makes the input fields render once 🤔

**Comment by ShanaLMoore** [comment] 2023-10-05 14:32
There's something about fontselect that adds another input field. I've since confirmed that this is happening on hyku proper's main, as well: 

I think this is happening because the two javascript files w font select are being called twice. I'm not sure why this would suddenly fail since the code isn't new, but removing one of these js files should solve the double rendering problem. 

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/4210dd7d-c367-4d65-a84c-ee99b61bab4e)

**Comment by ShanaLMoore** [comment] 2023-10-05 18:15
There is a known bug in hyku regarding the font display in the dropdown. For now you will have to click into a drop down option before it will update its rendering. This is out of scope to fix now and the fix should go back to hyku.

**Comment by ShanaLMoore** [comment] 2023-10-05 18:20
font needs to be https://fonts.googleapis.com/css?family=Nobile|sans-serif

**Comment by jillpe** [comment] 2023-10-11 16:19
SoftServ QA: 

- [x] DOUBLE RENDERING: There should be 1 input field for each option (Select Body Font and Select Header Font)
- [x] NO FONT DEFAULT PREVIEW:
  - Disregard. This is a known bug in hyku that we will not fix in this epic of work. Currently the user has to select an option of the dropdown to see the fonts displayed.


<details><summary>Screenshots</summary>


![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/69278fab-f243-4319-91f9-e0bca95bba64)



![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/c67cdd1d-b0b8-4c1e-a469-2f5bd8f120a7)



</details>

**Closed** 2024-04-18 23:18 UTC
Labels: Knapsack Upgrade, Internal Bug
