### ISSUE TITLE
🎁 Implement Persistent Highlighting

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#470] opened 2023-06-22 19:09 UTC
# Summary
Currently when you search a term in the catalog it highlights a snippet of the where it occurs in the work. When you click that work the search term does not persist, and you need to re-type it in the UV search. ADL would like to eliminate the multi-step process and have the search term persist from the catalog to the UV when you open the work. 

# Acceptance Criteria
- [ ] search term used in catalog persists to UV search when you click into the work

# Testing Instructions
- [ ] search for an ocr term in the catalog search
- [ ] if there is a match, click into it and the term should be highlighted in the universal viewer.

# Screenshots

### Searched for the word 'cat' in [staging](https://adl.s2.adventistdigitallibrary.org/catalog?utf8=%E2%9C%93&search_field=all_fields&q=cat):
<img width="996" alt="image" src="https://github.com/scientist-softserv/adventist-dl/assets/10081604/36e52e32-b778-49d8-a2fa-51f1856142ee">

### Clicking into the match should highlighted the word: 
<img width="887" alt="image" src="https://github.com/scientist-softserv/adventist-dl/assets/10081604/3fbc5c4e-9034-45b6-a61e-e6137834c76f">

**Comment by ShanaLMoore** [comment] 2023-06-22 19:57
In our client iteration meeting I couldn't remember if this feature was already implemented. If so, then this ticket should be a bug because it's no longer working. 

EDIT: Kirk confirmed that it was never implemented for ADL. 


ref: https://github.com/scientist-softserv/iiif_print/#catalog-to-universal-viewer-search

**Comment by DiemBTran** [comment] 2023-06-26 22:01
**Needs further review:**

Works tested on:
- https://sdapi.s2.adventistdigitallibrary.org/concern/published_works/7f52874c-87fc-4cda-b3fa-a22625618226?locale=en&parent_query=CLAUSEN
- https://sdapi.s2.adventistdigitallibrary.org/concern/journal_articles/91bb399f-6aa7-442a-82b6-49405e100c46?locale=en
- https://sdapi.s2.adventistdigitallibrary.org/concern/datasets/b14bff8c-528a-4230-94b2-fbcf65f2fd6b?locale=en

1. I did OCR term searches in the catalog search for all 3 of the above works
   1. screen recording: https://share.getcloudapp.com/4guXJe0r   
   1. sometimes the search works fine: catalog search loads correctly, the text is highlighted in the catalog, and clicking into the work shows that the OCR text is highlighted :white_check_mark: 
      1. timestamps in screen recording:
         1. 0:25 `please stare into my eyes`
         1. 1:20 `cat-scan` 
  1. other times, doing a search leads to a `We're sorry, but something went wrong.` page :x:
      1. timestamps in screen recording:
         1. 0:50 `for one minute`
         1. 1:30 `cat-scan is now complete`
      1. [link to Sentry error](https://scientist-inc.sentry.io/issues/4276701589/?project=6745020&referrer=project-issue-stream)
1. Additionally, it seems like the UV is catching an OCR term twice
   1. [screenshot](https://share.getcloudapp.com/Wnu6rDBk)
   1. The OCR term only actually appears in the .txt file once, but the UV says that there are 2 results. Clicking `Next Result` will just lead you back to the same, single highlighted result

**Comment by ShanaLMoore** [comment] 2023-06-26 22:17
<img width="1340" alt="image" src="https://github.com/scientist-softserv/adventist-dl/assets/10081604/dd1031fc-d487-4fce-b6c5-3d59b8da2011">

**Comment by laritakr** [comment] 2023-06-28 19:46
PDF splitting is currently broken in Adventist and UTK, and the IiifPrint update implemented in this job may be the cause.

**Comment by laritakr** [comment] 2023-06-28 19:52
[The PR also caused this error in staging](https://scientist-inc.sentry.io/issues/4278561363/events/30c0aee28b9547f9bc7dc97692617a0e/)

**Comment by jillpe** [comment] 2023-06-29 16:06
Possibly related to 
- #469

**Comment by ShanaLMoore** [comment] 2023-06-30 23:13
Blocked until filesets are reindexed on staging.

**Comment by DiemBTran** [comment] 2023-07-05 18:32
**This passes SoftServ QA:** See attached screen recording.

tested on:
- search query: https://sdapi.s2.adventistdigitallibrary.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=cat-scan+is+now+complete
- work show page: https://sdapi.s2.adventistdigitallibrary.org/concern/journal_articles/91bb399f-6aa7-442a-82b6-49405e100c46?locale=en&parent_query=cat-scan+is+now+complete

<details><summary>"cat-scan is now complete" was previously not searching correctly, but that is now fixed.</summary>

https://github.com/scientist-softserv/adventist-dl/assets/29311858/75ab887d-be6f-4165-8393-e8342c01393b
</details>

**Comment by KatharineV** [comment] 2023-07-10 13:20
I tested this using the term "Dederen," which appears in this work on staging: https://adl.s2.adventistdigitallibrary.org/concern/published_works/529f7a71-07af-4c1e-b005-de62726442f8?locale=en&parent_query=dederen

All worked as expected, and it looks great. Thanks for noting that a fix is coming for the hit count.

**Comment by KatharineV** [comment] 2023-07-18 14:59
I tested on production using the term "slaughter" which appears on several pages of this [work](https://adl.b2.adventistdigitallibrary.org/concern/published_works/22253238_spectrum_june_1996?locale=en&query=slaughter). 

The first instance of the keyword is highlighted in the viewer when I click into the work. It works as expected. Thank you!

![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/878efa19-e2c7-474a-a222-b4369bd370da)

**Closed** 2023-07-18 15:30 UTC
