### ISSUE TITLE
Adventist - Test IIIF Print

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#288] opened 2023-03-06 19:22 UTC
# Summary

After completing #278, #248, #286, #287,  #255 and #280 test the full functionality of IIIF Print on Adventist.

# Acceptance Criteria

- [x] As a user, I can view parent and child images grouped together in a manifest
- [x] As a user, when I upload an import, PDFs are split into component pages, OCR'd and derivative files are created for each page via a configurable job
- [x] As a user, I can configure the derivative generation for txt files
- [x] The gem is compatible with v2 and v3 manifest
- [x] As a user, when I select a work type, it's child works show up in the viewer under the parent item
- [x] As a user, I can easily navigate between child and parent works in the Universal Viewer and they appear in a logical order
- [x] As a user, I can see all of the metadata properties of a parent and child work in the Universal Viewer
- [x] As a user, I can zoom in on the the viewer
- [x] As a user, I can use paginated navigation
- [x] As a user, I can search the Universal Viewer for child or parent keywords
- [x] As a user, I can see my child or parent keyword searches highlighted on the show page
- [x] As a user, when I click on a viewer facet, it will redirect me to a search
- [x] As a user, I can download the text of a work in a txt format
- [x] As a user, I can add [/manifest.json] to the URL on a work show page to access its manifest in a JSON format

# Testing Instructions
**PDF Splitting**
The following should happen after creating a work and attaching a PDF to it via the UI, Bulkrax or CSV importer
- The PDF splits into childworks, with one PDF per page
- There should be a thumbnail associated with each childwork
- The childworks should be sorted via page number order
- The childworks should be the same model as the parent
- When you navigate into the childwork, json, txt, and xml formats should be available via the dropdown
  - [x] UI
  - [x] Bulkrax
    - [x] CSV

**UV**
The following should happen when you open a file in the viewer
- Each page of the PDF is represented by an image and is sorted by page number order in the left-side menu
- You can navigate through the pages via the paginated navigation at the top of the viewer or by clicking on the page in the left-side menu
- You can zoom in 
- The collapsable right-side menu contains metadata for the parent and child that is currently displayed
- Faceted metadata in the collapsable right-side menu is linked to that faceted search
- You can search for a child's metadata or text within the file via the text finder on the bottom part of the UV, and the text is highlighted where it appears
  - [x] UI
  - [x] Bulkrax
    - [x] CSV

**Catalog Search**
A catalog search for parent/child metadata or text within the file results in ONLY the parent work being returned in the catalog search
  - [x] UI
  - [x] Bulkrax
    - [x] CSV

# Notes

**Comment by KatharineV** [comment] 2023-03-28 15:11
Since this ticket is waiting for me to do _something_ in Client QA, I've tested what I can of this ticket using uploads to production while staging is tied up. Caveat: I tested as best I could, based on what I know how to do with the UV and the UI. My comments are below in bold. 

Here is the [example work](https://adl.b2.adventistdigitallibrary.org/concern/published_works/20088808_atlantic_union_gleaner_february_4_1903?locale=en) that I used the most for testing, and here is the [importer ](https://adl.b2.adventistdigitallibrary.org/importers/49?locale=en)that brought that work into production.

Acceptance Criteria

- [ ]     As a user, I can view parent and child images grouped together in a manifest. **Yes, if manifest means the UV and/or the item list on the parent work.**
- [ ]     As a user, when I upload an import, PDFs are split into component pages, OCR'd, and derivative files are created for each page via a configurable job. **Yes AND No. The PDF split and derivatives are present, but I can't search in the UV, so I wonder if OCR failed. All keywords return "no matches found."**
- [ ]     As a user, I can configure the derivative generation for txt files. **No, as far as I can tell. I do not see a way to configure derivatives for TXT files at any point.**
- [ ]     The gem is compatible with v2 and v3 manifest. **I don't know what this means, so I did not test it.**
- [ ]     As a user, when I select a work type, it's child works show up in the viewer under the parent item. **Yes, if "select a work type" means that I open a single work (that contains a PDF, for example) and see child works contained in the parent UV.**
- [ ]     As a user, I can easily navigate between child and parent works in the Universal Viewer and they appear in a logical order. **Yes, maybe? I only see derivatives/child works in the UV, so I don't know if I can "navigate" to the parent work, other than the fact that the UV is in the parent work and child works are in the UV. Yes, child works appear in logical order.**
- [ ]     As a user, I can see all of the metadata properties of a parent and child work in the Universal Viewer. **Yes.**
- [ ]     As a user, I can zoom in on the the viewer. **Yes.**
- [ ]     As a user, I can use paginated navigation. **Yes.**
- [ ]     As a user, I can search the Universal Viewer for child or parent keywords. **No. Keyword search does not work across any examples I tested.**
- [ ]     As a user, I can see my child or parent keyword searches highlighted on the show page **No.**
- [ ]     As a user, when I click on a viewer facet, it will redirect me to a search. **Yes.**
- [ ]     As a user, I can download the text of a work in a txt format. **No. I only see TXT download available where we've uploaded a TXT file to a work. The action drop downs do not list TXT as a format for any uploaded files or derivatives that I see, except the original TXT and the thumbnail JPEG we've uploaded via Bulkrax.**
- [ ]     As a user, I can add [/manifest.json] to the URL on a work show page to access its manifest in a JSON format. **Yes** [example](https://adl.b2.adventistdigitallibrary.org/concern/published_works/20088808_atlantic_union_gleaner_february_4_1903/manifest.json)

**Comment by laritakr** [comment] 2023-04-07 16:12
Referencing above checklist items which are not checked off by Katharine: 
1. OCR searching is now fixed.
2. Derivative creation is configurable via config files in the code.
3. Navigating from a child to the parent isn't really available. Normally you will begin on the parent work where you can see all of the children in the UV, or can click on any child in the list, and then use the back arrow to get to the parent. However, with the new child work naming structure, the parent work's id or slug is the last portion of the child work's title, so you can navigate directly to a parent using that.
4. Searching for a keyword brings up the parent work of the children that have that keyword. It does not indicate which child work has the given keyword. 
5. The keyword is not highlighted on a show page.
6. OCR text is downloadable when text derivatives are run (individual words). Full text is not available as an option.

The behavior is as expected, however the checklist used is not representative of expected behavior.

**Comment by jillpe** [comment] 2023-04-14 17:09
New Testing instructions:

**PDF Splitting**
The following should happen after creating a work and attaching a PDF to it via the UI, Bulkrax or CSV importer

The PDF splits into childworks, with one PDF per page
There should be a thumbnail associated with each childwork
The childworks should be sorted via page number order
The childworks should be the same model as the parent
When you navigate into the childwork, json, txt, and xml formats should be available via the dropdown
  - [ ] UI
  - [ ] Bulkrax
  - [ ] CSV


**UV**
The following should happen when you open a file in the viewer

Each page of the PDF is represented by an image and is sorted by page number order in the left-side menu
You can navigate through the pages via the paginated navigation at the top of the viewer or by clicking on the page in the left-side menu
You can zoom in
The collapsable right-side menu contains metadata for the parent and child that is currently displayed
Faceted metadata in the collapsable right-side menu is linked to that faceted search
You can search for parent/child metadata or text within the file via the text finder on the bottom part of the UV, and the text is highlighted where it appears
  - [ ] UI
  - [ ] Bulkrax
  - [ ] CSV

**Catalog Search**
A catalog search for parent/child metadata or text within the file results in ONLY the parent work being returned in the catalog search
  - [ ] UI
  - [ ] Bulkrax
  - [ ] CSV

**Comment by DiemBTran** [comment] 2023-04-19 16:59
**Needs further review:** Paired with Kirk

tested on:
- work created through UI: https://sdapi.s2.adventistdigitallibrary.org/concern/images/0ab556de-8b13-42a1-898c-048c8496ca61?locale=en
- work imported through Bulkrax: https://sdapi.s2.adventistdigitallibrary.org/concern/datasets/3de4e6c7-7295-4a3b-be6b-67f726070229?locale=en
  - link to importer: https://sdapi.s2.adventistdigitallibrary.org/importers/31?locale=en

# Testing instructions

- You can search for a child's metadata or text within the file via the text finder on the bottom part of the UV, and the text is highlighted where it appears
  - Child metadata search is not working for some fields, e.g. `contributor` field
  - [ ] UI
  - [ ] Bulkrax
    - [ ] CSV

**Comment by DeonFranklin** [comment] 2023-05-22 16:11
Noting the metadata search was fixed with this pr:
https://github.com/scientist-softserv/adventist-dl/pull/412

**Comment by DiemBTran** [comment] 2023-05-25 16:46
**This passes SoftServ QA:** See attached screenshots.

tested on:
- UI work: https://sdapi.s2.adventistdigitallibrary.org/concern/published_works/7f52874c-87fc-4cda-b3fa-a22625618226?locale=en
- Bulkrax work: https://sdapi.s2.adventistdigitallibrary.org/concern/datasets/b14bff8c-528a-4230-94b2-fbcf65f2fd6b?locale=en
  - importer: https://sdapi.s2.adventistdigitallibrary.org/importers/48?locale=en

<details><summary>Pagination works, pages are in number order, OCR works, and search facets work as expected.</summary>

![Published Work 2023-05-25 Adventist - Test IIIF Print #288 ID 7f52874c-87fc-4cda-b3fa-a22625618226 Hyku 2023-05-25 at 9 38 56 AM](https://github.com/scientist-softserv/adventist-dl/assets/29311858/1845a6e9-c15e-4e57-aca2-c1e5c1774361)
![Published Work 2023-05-25 Adventist - Test IIIF Print #288 ID 7f52874c-87fc-4cda-b3fa-a22625618226 Hyku 2023-05-25 at 9 39 10 AM](https://github.com/scientist-softserv/adventist-dl/assets/29311858/c2a731d1-263e-49a8-b898-05d4592bae88)
</details>

**Closed** 2023-09-12 14:17 UTC
Labels: Phase3/4, iiif_print
